### ISSUE TITLE
如果使用webui是否还需要用 ChatGLM-6B-API？

### ISSUE THREAD

**Issue by dongfengruhua** [QNLanYang/nonebot_plugin_ChatGLM6B#10]
我试过不用和用了机器人都不回复信息
戳一戳还是正常的
![image](https://user-images.githubusercontent.com/127479032/227709133-265c65bd-095a-4c63-8c43-cff5cfbc47be.png)

**Comment by QNLanYang** [comment]
你好，首先感谢你使用我的插件。
我的插件在开发的时候只参考了ChatGLM-6B-API，不同的API作者可能会使用不同的代码或不同的返回值，这可能导致无法正确发送请求或无法解析返回值。
未来我会考虑加入对webUI的API支持，等我研究研究，最近有一些考试。
目前推荐的使用方法是把chatglm-api.py放到webui的根目录（如果你用的是B站UP秋叶的webui整合包），修改其中模型路径，然后仿照整合包中的.bat文件写一个启动API的，这样就可以用webui的虚拟环境直接启动。

**Comment by QNLanYang** [comment]
所以答案是：是的，目前你仍然需要ChatGLM-6B-API。
可惜的就是可能没法和webui一起开，因为会占两份显存

**Comment by QNLanYang** [comment]
所以答案是：是的，目前你仍然需要ChatGLM-6B-API。
可惜的就是可能没法和webui一起开，因为会占两份显存

**Comment by QNLanYang** [comment]
@dongfengruhua 我更新的 [v0.1.2](https://github.com/QNLanYang/nonebot_plugin_ChatGLM6B/releases/tag/v0.1.2) 加入了对官方API的支持，但是webui的方法我还没研究出来。

**Comment by dongfengruhua** [comment]
谢谢您
