### ISSUE TITLE
按要求填写了配置，但是无法访问api

### ISSUE THREAD

**Issue by 54108** [QNLanYang/nonebot_plugin_ChatGLM6B#24]
![屏幕截图 2023-04-14 233917](https://user-images.githubusercontent.com/64118954/232090989-ad4b1d4a-e84b-42e0-b59a-27dd9574b07d.png)
如图，很困扰（话说作者为啥不留一个qq或者啥群方便交流）
（年轻人的第一个issue）

**Comment by QNLanYang** [comment]
首先感谢你使用我的插件，没有留QQ主要是因为感觉不会有多少人用，如果你要的话这是我的B站粉丝群： `816388102`

目前来看你的问题应该出在bot本身的配置上，怀疑是没有以 `.env.prod` 作为环境读取参数，请检查你的 `.env` 文件中的 `ENVIRONMENT` 值是否等于 `prod`。

此外，建议你写http就可以，https不一定行得通。

**Comment by 54108** [comment]
关于配置问题，按要求配置即可。对于我这种几乎没有插件的机器人，回复机器人时的指令应为/#xxx（xxx即为你想发送的内容）

**Comment by QNLanYang** [comment]
是的，以下是一些补充说明：
如果机器人配置文件未填写 `COMMAND_START` （命令前缀）则默认前缀为 `/`
则以下是对话的正确用法： `/GLM 你好！` 或 `/# 你好！`
