### ISSUE TITLE
成功配置api.py后在nonebot上无应答

### ISSUE THREAD

**Issue by MINTDUCKK** [QNLanYang/nonebot_plugin_ChatGLM6B#25]
您好，我是萌新一枚，今天我成功在我的pc上运行了官方的API.py，并产生如下运行图
![image](https://user-images.githubusercontent.com/129481245/232453636-39b38fd8-8b55-4743-8022-16d7315d590d.png)
然而，在我运行nonebot时，问答依然无响应，
![image](https://user-images.githubusercontent.com/129481245/232453795-daae7997-08bf-42e8-89bb-df5223d5e673.png)
我认为我的配置没有问题，但是实在不知道还有哪里可以修改，所以想请教您是哪里出了问题>_<
![image](https://user-images.githubusercontent.com/129481245/232454159-f12b7af6-92e2-47ee-919f-600c9eb99403.png)
如能赐教，不胜感激！><

**Comment by QNLanYang** [comment]
#24 

你可以看看这个issue，如果没有设置bot的命令前缀 `COMMAND_START` 参数，则默认的前缀为 `/` 。
_（另外你的bot运行日志只截取到收到消息，所以我无法得知收到消息后是否触发响应器，所以这个是我猜的，你先试试这个方法）_
也就是说你要触发本插件响应必须使用 `/# 你好` 或 `/GLM 你好` 。

**Comment by MINTDUCKK** [comment]
非常非常非常感谢！确实是没有添加命令前缀！！不胜感激（确实是我太菜了） 如果有未来使用过程中的问题我一定会积极向您反馈的:D

**Comment by QNLanYang** [comment]
好滴好滴，非常感谢你使用我的插件~
